### ISSUE TITLE
Increase minor kernel version range 

### ISSUE THREAD

**Issue by nodeax** [gregkh/kernel-history#2]
Currently 4.4.x and 4.9.x kernel minor version ranges are beyond 200 resulting in stats not being printed for anything about x.y.200. Hence increase the range to check for.

Fix: https://github.com/nodeax/kernel-history/commit/6c119061ec4d5177ac8b681240be1ac954e358ed

Thanks.

**Comment by gregkh** [comment]
Thanks, I've bumped this to 400 just to "be safe" for now
